package com.bydmate.app.service

import com.bydmate.app.data.repository.SettingsRepository
import com.bydmate.app.domain.CloudSocPreference
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.distinctUntilChanged
import java.io.File

/**
 * The app-side half of the survival daemon's config: Room settings rendered as the
 * `voltflow_cmd.conf` key=value file [com.bydmate.app.daemon.CommandDaemon] reads.
 *
 * The daemon runs as uid shell and cannot read our settings DB, so this file is its only view
 * of them. Chain: [observe] re-renders on every change of an exported key → [TrackingService]
 * writes it to `<externalFilesDir>/voltflow_cmd.conf` → the watchdog in
 * `start_voltflow_cmd.sh` copies it to `/data/local/tmp/voltflow_cmd.conf` every 30 s → the
 * daemon re-reads that on every loop iteration.
 *
 * B-18: the file used to be written only when TrackingService started, so a toggle flipped
 * while the service was running never reached the daemon. Measured on car `way`: Room said
 * keep-WiFi `false` while the daemon's file said `keep_wifi_awake=1`.
 */
object DaemonConfigExport {

    const val FILE_NAME = "voltflow_cmd.conf"

    /**
     * Null when cloud sync is not linked yet — the caller then leaves any existing file alone,
     * exactly as the one-shot export did.
     */
    fun render(
        url: String,
        apiKey: String,
        vehicleId: String,
        keepWifiAwake: Boolean,
        vehicleUid: String? = null,
        socPreference: CloudSocPreference = CloudSocPreference.DIPLUS_FIRST,
    ): String? {
        val u = url.trim()
        val k = apiKey.trim()
        val v = vehicleId.trim()
        if (u.isBlank() || k.isBlank() || v.isBlank()) return null
        // B-03: the daemon sends the same X-Vehicle-Uid as the app, so both store under one key.
        val uid = vehicleUid?.trim()?.takeIf { it.isNotBlank() }?.let { "vehicle_uid=$it\n" }.orEmpty()
        // Only the non-default is written: an absent key means Di+-first, so a conf from before
        // this switch (or an older daemon that ignores unknown keys) behaves exactly as it did.
        val soc = if (socPreference == CloudSocPreference.DIPLUS_FIRST) "" else "soc_source=${socPreference.wireName}\n"
        return "# auto-generated by VoltFlow Mate — consumed by start_voltflow_cmd.sh\n" +
            "url=$u\napi_key=$k\nvehicle_id=$v\n" + uid +
            "keep_wifi_awake=${if (keepWifiAwake) 1 else 0}\n" + soc
    }

    /** Current rendering, re-emitted whenever any exported setting changes. */
    fun observe(repo: SettingsRepository): Flow<String?> = combine(
        repo.observeString(SettingsRepository.KEY_CLOUD_SYNC_URL),
        repo.observeString(SettingsRepository.KEY_CLOUD_SYNC_API_KEY),
        repo.observeString(SettingsRepository.KEY_CLOUD_SYNC_VEHICLE_ID),
        repo.observeString(SettingsRepository.KEY_CLOUD_SYNC_KEEP_WIFI_AWAKE),
        repo.observeString(SettingsRepository.KEY_CLOUD_SYNC_VEHICLE_UID),
        repo.observeString(SettingsRepository.KEY_CLOUD_SOC_SOURCE),
    ) { v ->
        render(
            url = v[0].orEmpty(),
            apiKey = v[1].orEmpty(),
            vehicleId = v[2].orEmpty(),
            keepWifiAwake = v[3] == "true",
            vehicleUid = v[4],
            socPreference = CloudSocPreference.fromWire(v[5]),
        )
    }.distinctUntilChanged()

    /**
     * Temp file + rename, so the watchdog's `cp` never picks up a half-written file (the daemon
     * would read it as incomplete and skip that iteration).
     */
    fun write(dir: File, text: String): File {
        val target = File(dir, FILE_NAME)
        val tmp = File(dir, "$FILE_NAME.tmp")
        tmp.writeText(text)
        if (!tmp.renameTo(target)) {
            tmp.delete()
            target.writeText(text)
        }
        return target
    }
}
