package com.bydmate.app.service

import com.bydmate.app.data.repository.SettingsRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.distinctUntilChanged
import java.io.File

/**
 * The app-side half of the survival daemon's config: Room settings rendered as the
 * `voltflow_cmd.conf` key=value file [com.bydmate.app.daemon.CommandDaemon] reads.
 *
 * The daemon runs as uid shell and cannot read our settings DB, so this file is its only view
 * of them. Chain: [observe] re-renders on every change of an exported key → [TrackingService]
 * writes it to `<externalFilesDir>/voltflow_cmd.conf` → the watchdog in
 * `start_voltflow_cmd.sh` copies it to `/data/local/tmp/voltflow_cmd.conf` every 30 s → the
 * daemon re-reads that on every loop iteration.
 *
 * B-18: the file used to be written only when TrackingService started, so a toggle flipped
 * while the service was running never reached the daemon. Measured on car `way`: Room said
 * keep-WiFi `false` while the daemon's file said `keep_wifi_awake=1`.
 */
object DaemonConfigExport {

    const val FILE_NAME = "voltflow_cmd.conf"

    /**
     * Null when cloud sync is not linked yet — the caller then leaves any existing file alone,
     * exactly as the one-shot export did.
     */
    fun render(url: String, apiKey: String, vehicleId: String, keepWifiAwake: Boolean): String? {
        val u = url.trim()
        val k = apiKey.trim()
        val v = vehicleId.trim()
        if (u.isBlank() || k.isBlank() || v.isBlank()) return null
        return "# auto-generated by VoltFlow Mate — consumed by start_voltflow_cmd.sh\n" +
            "url=$u\napi_key=$k\nvehicle_id=$v\n" +
            "keep_wifi_awake=${if (keepWifiAwake) 1 else 0}\n"
    }

    /** Current rendering, re-emitted whenever any exported setting changes. */
    fun observe(repo: SettingsRepository): Flow<String?> = combine(
        repo.observeString(SettingsRepository.KEY_CLOUD_SYNC_URL),
        repo.observeString(SettingsRepository.KEY_CLOUD_SYNC_API_KEY),
        repo.observeString(SettingsRepository.KEY_CLOUD_SYNC_VEHICLE_ID),
        repo.observeString(SettingsRepository.KEY_CLOUD_SYNC_KEEP_WIFI_AWAKE),
    ) { url, apiKey, vehicleId, keepWifi ->
        render(url.orEmpty(), apiKey.orEmpty(), vehicleId.orEmpty(), keepWifi == "true")
    }.distinctUntilChanged()

    /**
     * Temp file + rename, so the watchdog's `cp` never picks up a half-written file (the daemon
     * would read it as incomplete and skip that iteration).
     */
    fun write(dir: File, text: String): File {
        val target = File(dir, FILE_NAME)
        val tmp = File(dir, "$FILE_NAME.tmp")
        tmp.writeText(text)
        if (!tmp.renameTo(target)) {
            tmp.delete()
            target.writeText(text)
        }
        return target
    }
}
